### ISSUE TITLE
No more "--complement" option?

### ISSUE THREAD

**Issue by map2085** [smarco/gem3-mapper#1]
I am excited to see renewed maintenance and development of GEM.  It is the only aligner I can trust to report all alignments for each read within given error thresholds.

In the GEM Beta build 1.376 (beta) - (2013/04/06 02:13:06 GMT), there was an option in the indexer for "--complement no" which would force mapping reads to the forward strand only.  This is useful for Stranded RNA-seq data, which is very common nowadays.

I do not see the "--complement" option in GEMv3.  
How can I make GEMv3 do strand-specific mapping?

Thank you.

**Comment by smarco** [comment]
Good to hear that.

The point is that I didn't had the feeling that no-complement index option was being used. But, if that is the case, I can easily push an update to support it again.

Thanks for the feedback.
Best,

**Comment by smarco** [comment]
Update: --complement=no option has been made available since the commit 9626409.

**Comment by y9c** [comment]
`--complement` option is missing again in the latest code?

**Comment by smarco** [comment]
Hi,

There should be the option on the `gem-indexer` at [here](https://github.com/smarco/gem3-mapper/blob/82cfcaa0b5ab0c09a94d48375b25883b9d31caf2/src/tools/gem-indexer.c#L279).

**Comment by y9c** [comment]
Is it possible to use this option in the mapper?

**Comment by smarco** [comment]
No, I am afraid that the index has to be regenerated.

**Comment by y9c** [comment]
Thank you @smarco.
