### ISSUE TITLE
clang: error: unsupported option '-fopenmp'

### ISSUE THREAD

**Issue by hwlim** [smarco/gem3-mapper#11]
I tried 'make' but got an error:

> clang: error: unsupported option '-fopenmp'

My OS is Mac OS Mojave. It seems like some other R package compilation has a similar problem, which I figured out by making ~/.R/Makrvar file containing

> CC=/usr/local/opt/llvm/bin/clang
> CXX=/usr/local/opt/llvm/bin/clang++
> CXX11=/usr/local/opt/llvm/bin/clang++
> CXX14=/usr/local/opt/llvm/bin/clang++
> CXX16=/usr/local/opt/llvm/bin/clang++
> CXX1X=/usr/local/opt/llvm/bin/clang++
> LDFLAGS=-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib
> FLIBS=-L/usr/local/Cellar/gcc/8.3.0/lib/gcc/8

However, I don't know how to handle this case, which is not R. Any idea?

**Comment by smarco** [comment]
Do you have OpenMP installed?
e.g. brew install clang-omp

**Comment by hwlim** [comment]
In the recent version, "brew install clang-omp" doesn't work out.
Instead, I installed it via "brew install llvm".  Somehow the environment for openmp has changed in Mac OS. It seems like the previously used default path or setting is not compatible with the new environment anymore. I see similar errors in other package installation using openmp. I figured how to make it in R as mentioned above. But not in this case.

**Comment by heathsc** [comment]
The configure script checks for the OpenMP headers.  In this case it looks like the headers are present on the system but the clang version you are using does not support openmp (as far as I know, the default MacOS chain does not support openmp).  In this case you can simply edit Makefile.mk in the root gem3-mapper directory (after running ./configure) and change the line with HAVE_OPENMP = 1 to HAVE_OPENMP = 0, and then retry the make.  OpenMP is little used in GEM3 so you can work very well without it.

Simon

**Comment by hwlim** [comment]
Great! It works! Thank you!
