### ISSUE TITLE
cannot use --gpu 

### ISSUE THREAD

**Issue by sleepvet** [smarco/gem3-mapper#15]
When I use gem, I cannot use _--gpu_ to accelarate my run. It simply tells me unrecognised option "--gpu". My gem version is 3.6.1-21-g2386-dirty-release. My computer has a NVIDIA Quadro P2000 gpu.

**Comment by smarco** [comment]
Hi,

You must make sure that the gem-mapper has been compiled for GPU. That is, when you execute the "./configure" before the "make clean all", make sure your GPU card is correctly detected. Otherwise, all GPU support is disabled and not even the compilation option "--gpu" is available.

**Comment by sleepvet** [comment]
> Hi,
> 
> You must make sure that the gem-mapper has been compiled for GPU. That is, when you execute the "./configure" before the "make clean all", make sure your GPU card is correctly detected. Otherwise, all GPU support is disabled and not even the compilation option "--gpu" is available.

File  .configure tells cuba lib is not found in my computer. It looks like a headache gpu driver install step was failed. I will close this issue, thank you very much!
