### ISSUE TITLE
how do GEM accept input from pipe 

### ISSUE THREAD

**Issue by sleepvet** [smarco/gem3-mapper#16]
I donot want to output a temporary file. Here is what I did:
cat /mnt/\*.fa|gem-indexer -i -o newsuper
cat /mnt/\*.fa|gem-indexer  -o newsuper
cat /mnt/*.fa|gem-indexer -i - -o newsuper
But none of them worked. Could please help me with it?

**Comment by smarco** [comment]
I'm afraid you will have to create this temporal file. The gem-indexer executes a rewind of the input file, so it needs it to be stored (so it can be read twice).

Sorry for the inconvenience,
