### ISSUE TITLE
gem-indexer and tmp file

### ISSUE THREAD

**Issue by descostesn** [smarco/gem3-mapper#20]
Hi,

When using the gem-indexer, I get the error `Could not write to file 'chr1.sa.tmp'`.

This is because this file is written to my home folder that has only 800 mb of space on our hpc.

Is it possible to redirect the location of this temporary file?

Thanks for you help.

Nicolas

**Comment by smarco** [comment]
Yes. The easiest option is to change the working directory from which you call the gem-indexer.

> cd /tmp
> /usr/local/bin/gem-mapper [...]

**Comment by descostesn** [comment]
I am not calling it from my home directory, however it is putting this file in the home directory by default. If you mean something different, I do not get it.

**Comment by smarco** [comment]
By default, it puts all the temporal files where the command specifies. That is:

```
cd /tmp
/usr/local/bin/gem-mapper -i /data/chr1.fa -o /tmp/chr1
```

Will save everything on the temporal folder '/tmp'
However, you can always use the option '--tmp-folder=/tmp/'
I hope this helps.

**Comment by descostesn** [comment]
Thank you. At the end I redirected my home folder to a share drive on the hpc and it worked.
