### ISSUE TITLE
question about the control sequences

### ISSUE THREAD

**Issue by biozzq** [smarco/gem3-mapper#21]
Dear all,

I think the question I raised in https://github.com/heathsc/gemBS/issues/81 should be better here. Thank you for your time.

Best wishes,
Zheng zhuqing

**Comment by smarco** [comment]
Hi,

In fact, all the issues related to the gemBS should be addressed in the gemBS git-repo.
Here you can specify questions about the GEM-mapper standalone.

Thanks.
Cheers,
