### ISSUE TITLE
questions about gem-mapper

### ISSUE THREAD

**Issue by biozzq** [smarco/gem3-mapper#22]
Dear @smarco 

I think this question ( https://github.com/smarco/gem3-mapper/issues/21) should be related to gem-mapper, I just want to know how to set the  `--underconversion-sequence`, `--overconversion-sequence`, and `--control-sequence` optimally.
```
 [Bisulfite and Hi-C Alignment]
      --bisulfite-conversion 'inferred-C2T-G2A','inferred-G2A-C2T','C2T','G2A','non-stranded' (default=inferred-C2T-G2A)
      --underconversion-sequence <sequence name> (default=NC_001416.1)
      --overconversion-sequence <sequence name> (default=NC_001604.1)
      --control-sequence <sequence name> (default=NC_001422.1)
```
Best wishes,
Zheng zhuqing

**Comment by heathsc** [comment]
Dear Zheng,

The questions relate more to the functions of the mapper within the gemBS
pipeline than to the basic mapping functions themselves.

The conversion and control sequences should be set to the names of the
sequences that were added into the sequence library to act as controls.  If
these are not set correctly then gemBS will not be able to estimate the
conversion rates, but it will not affect the mapping process.  For Illumina
sequencing the control sequence is typically Phi-X (NC_001422.1), and for
WGBS sequencing the undeconversion control (if used) is often Phage lambda
(NC_001416.1).  There is no widely used over conversion sequence as far as
I know.  Note that the conversion sequences should be included in the
reference FASTA file used to build the GEM mapping index.

The --bisulfite-conversion option allows different sequencing library
characteristics.

Stranded libraries:

inferred-C2T-G2A      Read 1 is C depleted, read 2 is G depleted (most
common configuration)
inferred-G2A-C2T      Read 1 is G depleted, read 2 is C depleted
C2T                           All reads are C depleted
G2A                           All reads are G depleted

Non stranded libraries

non-stranded             Each read pair can either be C2T-G2A or G2A-C2T
independently of the other reads

Simon

**Comment by biozzq** [comment]
Dear Simon,

Thank you for your explanation.

Best wishes,
Zheng zhuqing
