### ISSUE TITLE
Compilation failure: zlib.h: No such file or directory

### ISSUE THREAD

**Issue by EmmettPeng** [smarco/gem3-mapper#26]
Hi,

The compilation was terminated with warnings:
```
fm.c:30:10: fatal error: zlib.h: No such file or directory
 #include <zlib.h>
          ^~~~~~~~
compilation terminated.
make[2]: *** [Makefile:65: ../../build/fm.o] Error 1
make[2]: Leaving directory '/home/pengxi/softwares/gem3-mapper/src/system'
make[1]: *** [Makefile:71: system] Error 2
make[1]: Leaving directory '/home/pengxi/softwares/gem3-mapper/src'
make: *** [Makefile:33: release] Error 2

```

I searched for some solutions online and installed zlib1g-dev package but the problem still did not go away. Is there any other solutions?

Any help will be greatly appreciated!

Emmett

**Comment by smarco** [comment]
Hi,

In principle, you could go for installing the missing library (e.g. on Ubuntu 'sudo apt-get install libz-dev') or just compile the gem mapper without zlib support. Then, running:

./configure

Should detect that you don't have the library installed. If that doesn't work, you can always deactivate it on 'Makefile.mk' and set:

HAVE_ZLIB = 0

I hope this helps.
Best,
