### ISSUE TITLE
gem-indexer finished with error

### ISSUE THREAD

**Issue by alkurowska** [smarco/gem3-mapper#28]
hello, 

I am running indexer on my fasta file and after it was succefully build I get the following error:

2021/9/4 19:52:10 -- [GEM Index 'Homo_sapiens_GRCh38.gem' was successfully built in 251.547 min.] (see 'Homo_sapiens_GRCh38.info' for further info)
*** Error in `gem-indexer': double free or corruption (!prev): 0x0000000000682360 ***

Also when I sue the created gem file in gem-mappability I get this error: 
Fatal error (setup.c:167,input_gem_header)
 Bad GEM header

Any suggestions?

**Comment by smarco** [comment]
Hello,

1) If the message " was successfully built" was printed, the gem file generated is correct and you should be able to work with it using GEM3 tools. In any case, we will debug this error message.

2) The tool gem-mappability comes within the GEM1 release and uses GEM1 index format. For that, you will have to use the tools within that distribution to get the index with the correct HEADER.

I hope this helps.
Best,

**Comment by alkurowska** [comment]
Thank you a lot!
