### ISSUE TITLE
installing older versions of gem-mapper

### ISSUE THREAD

**Issue by AprilJauhal** [smarco/gem3-mapper#34]
Hello, I tried running the binaries for the older version of gem-mapper from here: https://sourceforge.net/projects/gemlibrary/ and have been unsuccessful. I wasn't able to get any of the linux binaries to work locally via ubuntu or on my computing cluster. I checked and both are i3-compatible. When I try to run gem-mapper it simply says that the command is not found, even when I am in the bin directory containing the file. Is there any way I can still access the pre-GEM3 versions of gem-mapper?

Thank you!

**Comment by smarco** [comment]
Hi, can you share the precise commands you have executed (from downloading the binaries to their execution). I'm sure we can find a solution. Thanks,

**Comment by AprilJauhal** [comment]
Thank you, here is what I attempted. I downloaded the compressed files through the browser.  

$ tar -xvjf GEM-binaries-Linux-x86_64-core_i3-20130406-045632.tbz2
$ cd GEM-binaries-Linux-x86_64-core_i3-20130406-045632/bin
$ gem-mapper

Result was"gem-mapper: command not found," I also tried gem-mapper -h and gem-mapper --help

**Comment by smarco** [comment]
Ok, try this and let me know:
$ ./gem-mapper

**Comment by AprilJauhal** [comment]
That worked! However, I need to be able to add the binary to $PATH so that I can run gem-mapper as a dependency. Do you have any suggestions for that?

**Comment by smarco** [comment]
The classic: 
$ export PATH=$PATH:/path/to/gem/

See this article for [more](https://unix.stackexchange.com/questions/26047/how-to-correctly-add-a-path-to-path)

**Comment by AprilJauhal** [comment]
I am aware of how to add variables to the PATH, however adding the binary filepath to the path in that way wasn't working. Calling "gem-mapper" isn't working when I add either the filepath to the folder containing the binaries or the full path_to/gem-mapper to the PATH. I verified that these were added to the PATH via echo $PATH.
