### ISSUE TITLE
splicing mapping mode for RNA-seq is supported?

### ISSUE THREAD

**Issue by y9c** [smarco/gem3-mapper#35]
The document does not show an argument for splicing mapping for RNA-seq data, but the code shows RNA-seq filtering step. I wonder if this tool is comparable with RNA-seq data? 

Thank you. 

https://github.com/smarco/gem3-mapper/blob/82cfcaa0b5ab0c09a94d48375b25883b9d31caf2/resources/gem-tools/tools/gt.filter.c#L63C3-L67

**Comment by smarco** [comment]
The library has some functions to process SAM files produced by RNA mappers. One of the `gem-tools` goals was to facilitate the post-processing of SAM/MAP files. However, `gem-tools` is a different component than the mapper itself `gem-mapper`.

Let me know if this answers your question.

**Comment by y9c** [comment]
Thank you for the information.
