### ISSUE TITLE
Compilation failed in MacOS due to usage of sys/sysinfo

### ISSUE THREAD

**Issue by magicDGS** [smarco/gem3-mapper#6]
After `./configure` and `make`, the compilation fails with the following error:

```
gcc -Ofast -march=native -flto -std=c99 -Wall -DNDEBUG -I../../include -c mm.c -o ../../build/mm.o
mm.c:42:10: fatal error: 'sys/sysinfo.h' file not found
#include <sys/sysinfo.h>
         ^
1 error generated.
```

Is there any way of compile in MacOS even with that dependency? If not, I think that it is important to remove the dependency on `sys/sysinfo` to make gem-mapper platform-independent.

Thank you!

**Comment by magicDGS** [comment]
Conflicting lines are

https://github.com/smarco/gem3-mapper/blob/d4f486d1bfa1371903d6c7ded99b58f5cef45104/src/system/mm.c#L40-L43

It looks like if can be solved by removing line 40.

**Comment by smarco** [comment]
Thanks for reporting.
The "sys/sysinfo" dependency has been definitely removed.

Cheers,

**Comment by magicDGS** [comment]
Thanks!
